-- MySQL Script generated by MySQL Workbench
-- Fri Oct 30 19:44:10 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`pessoa` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`cliente` (
  `cpf` VARCHAR(11) NOT NULL,
  `status_pagamento` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  CONSTRAINT `cpf`
    FOREIGN KEY (`cpf`)
    REFERENCES `mydb`.`pessoa` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`obra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`obra` (
  `ID_Obra` INT NOT NULL,
  `tipo` VARCHAR(15) NOT NULL,
  `localizacao` VARCHAR(45) NOT NULL,
  `status_obra` VARCHAR(45) NOT NULL,
  `ID_Gerente` VARCHAR(45) NOT NULL,
  `ID_Engenheiro` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Obra`),
  UNIQUE INDEX `ID_Obra_UNIQUE` (`ID_Obra` ASC) VISIBLE,
  UNIQUE INDEX `ID_Gerente_UNIQUE` (`ID_Gerente` ASC) VISIBLE,
  UNIQUE INDEX `ID_Engenheiro_UNIQUE` (`ID_Engenheiro` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`funcionario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`funcionario` (
  `cpf` VARCHAR(11) NOT NULL,
  `salario` DECIMAL(7,2) NOT NULL,
  `data_admissao` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`cpf`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC) VISIBLE,
  CONSTRAINT `cpf_Func`
    FOREIGN KEY (`cpf`)
    REFERENCES `mydb`.`pessoa` (`cpf`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`documento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`documento` (
  `ID_Documento` INT NOT NULL,
  `ID_Responsavel` VARCHAR(11) NOT NULL,
  `situacao` VARCHAR(15) NOT NULL,
  `ID_Obra` INT NOT NULL,
  PRIMARY KEY (`ID_Documento`),
  UNIQUE INDEX `ID_Documento_UNIQUE` (`ID_Documento` ASC) VISIBLE,
  UNIQUE INDEX `ID_Obra_UNIQUE` (`ID_Obra` ASC) VISIBLE,
  INDEX `Responsavel_idx` (`ID_Responsavel` ASC) VISIBLE,
  CONSTRAINT `Obra`
    FOREIGN KEY (`ID_Obra`)
    REFERENCES `mydb`.`obra` (`ID_Obra`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `Responsavel`
    FOREIGN KEY (`ID_Responsavel`)
    REFERENCES `mydb`.`funcionario` (`cpf`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor` (
  `ID_Fornecedor` INT NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Fornecedor`),
  UNIQUE INDEX `ID_Fornecedor_UNIQUE` (`ID_Fornecedor` ASC) VISIBLE,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`fornece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fornece` (
  `ID_Obra` INT NOT NULL,
  `ID_Fornecedor` INT NOT NULL,
  `expiracao_contrato` DATETIME NOT NULL,
  PRIMARY KEY (`ID_Obra`, `ID_Fornecedor`),
  INDEX `Forneceddor_idx` (`ID_Fornecedor` ASC) VISIBLE,
  CONSTRAINT `Fornecedor_For`
    FOREIGN KEY (`ID_Fornecedor`)
    REFERENCES `mydb`.`fornecedor` (`ID_Fornecedor`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `Obra_For`
    FOREIGN KEY (`ID_Obra`)
    REFERENCES `mydb`.`obra` (`ID_Obra`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`fornecedor_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`fornecedor_produtos` (
  `ID_Fornecedor` INT NOT NULL,
  `produtos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Fornecedor`, `produtos`),
  CONSTRAINT `Fornecedor_ForPro`
    FOREIGN KEY (`ID_Fornecedor`)
    REFERENCES `mydb`.`fornecedor` (`ID_Fornecedor`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`obra_clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`obra_clientes` (
  `ID_Obra` INT NOT NULL,
  `ID_Cliente` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_Obra`, `ID_Cliente`),
  UNIQUE INDEX `ID_Cliente_UNIQUE` (`ID_Cliente` ASC) VISIBLE,
  UNIQUE INDEX `ID_Obra_UNIQUE` (`ID_Obra` ASC) VISIBLE,
  CONSTRAINT `ID_Cliente_ObraCli`
    FOREIGN KEY (`ID_Cliente`)
    REFERENCES `mydb`.`cliente` (`cpf`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `ID_Obra_ObraCli`
    FOREIGN KEY (`ID_Obra`)
    REFERENCES `mydb`.`obra` (`ID_Obra`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `mydb`.`participa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`participa` (
  `cpf` VARCHAR(11) NOT NULL,
  `ID_Obra` INT NOT NULL,
  `permissao` VARCHAR(15) NOT NULL,
  PRIMARY KEY (`cpf`, `ID_Obra`),
  INDEX `ID_Obra_idx` (`ID_Obra` ASC) VISIBLE,
  CONSTRAINT `cpf_Part`
    FOREIGN KEY (`cpf`)
    REFERENCES `mydb`.`pessoa` (`cpf`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `ID_Obra_Part`
    FOREIGN KEY (`ID_Obra`)
    REFERENCES `mydb`.`obra` (`ID_Obra`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

USE `mydb`;

DELIMITER $$
USE `mydb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `mydb`.`Cliente_BEFORE_INSERT`
BEFORE INSERT ON `mydb`.`cliente`
FOR EACH ROW
BEGIN
	IF NEW.cpf not in (
            select A.cpf
            From Funcionario A  -- CHANGED THE ALIAS TO A
            where (NEW.cpf = A.cpf)
        ) THEN -- MISSING THEN
		CALL `Insert not allowed`;
	END IF;
END$$

USE `mydb`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `mydb`.`Funcionario_BEFORE_INSERT`
BEFORE INSERT ON `mydb`.`funcionario`
FOR EACH ROW
BEGIN
	IF NEW.cpf not in (
            select A.cpf
            From Cliente A  -- CHANGED THE ALIAS TO A
            where (NEW.cpf = A.cpf)
        ) THEN -- MISSING THEN
		CALL `Insert not allowed`;
	END IF;
END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
